// Language translations for Health Sync website
const translations = {
  en: {
    // Navigation
    navHome: "Home",
    navSpecialist: "Specialist",
    navSubscription: "Subscription",
    navQuestions: "Questions",
    navVoiceInput: "Voice Input",
    navAbout: "About",
    navLogin: "Log in",
    navSignup: "Sign Up",
    navBookAppointment: "Book Appointment",
    
    // Hero Section
    heroKicker: "Trusted digital care ecosystem",
    heroTitle: "Your Health, ",
    heroTitleSpan: "Our Priority",
    heroSubtitle: "Experience the future of healthcare with Health Sync. Book appointments with top specialists, track your health with AI, and get emergency support when you need it most.",
    heroBookBtn: "Book Appointment",
    heroEmergencyBtn: "Emergency SOS",
    heroStatsDoctors: "Expert Doctors",
    heroStatsPatients: "Happy Patients",
    heroStatsSupport: "Emergency Support",
    heroHealthScore: "Health Score",
    heroHealthScoreValue: "98% Stable",
    
    // Specializations
    specHeader: "Find the Right Specialist",
    specDescription: "Connect with top-rated doctors across various specializations. Our platform ensures you get the best care from qualified professionals.",
    specCardiology: "Cardiology",
    specCardiologyDesc: "Heart and cardiovascular system specialists",
    specDermatology: "Dermatology",
    specDermatologyDesc: "Skin, hair, and nail care experts",
    specNeurology: "Neurology",
    specNeurologyDesc: "Brain and nervous system specialists",
    specGeneralPhysician: "General Physician",
    specGeneralPhysicianDesc: "Primary care and general health",
    specPediatrics: "Pediatrics",
    specPediatricsDesc: "Specialized care for children",
    specOrthopedics: "Orthopedics",
    specOrthopedicsDesc: "Bone, joint, and muscle specialists",
    specDoctorsAvailable: "doctors available",
    specOnlineNow: "Online now",
    specBookConsultation: "Book Consultation",
    specViewAll: "View All Specializations",
    
    // Features
    featuresHeader: "Smart Healthcare Features",
    featuresDescription: "Experience the future of healthcare with our innovative features designed to make your health management easier, smarter, and more effective.",
    featureAITracker: "AI Health Tracker",
    featureAITrackerDesc: "Advanced AI monitors your vital signs, symptoms, and health patterns to provide personalized insights and early warning alerts.",
    featureAITracker1: "Real-time monitoring and alerts",
    featureAITracker2: "Secure and HIPAA compliant",
    featureAITracker3: "24/7 accessibility",
    featureInstantAppointment: "Instant Appointment",
    featureInstantAppointmentDesc: "Book appointments with specialists instantly. No waiting rooms, no hassle. Get connected with the right doctor in minutes.",
    featureInstantAppointment1: "Smart specialist matching",
    featureInstantAppointment2: "Secure video consultations",
    featureInstantAppointment3: "Automated scheduling reminders",
    featureMedicineReminder: "Medicine Reminder",
    featureMedicineReminderDesc: "Never miss a dose again. Smart reminders ensure you take the right medication at the right time with dosage tracking.",
    featureMedicineReminder1: "Personalized schedules",
    featureMedicineReminder2: "Caregiver notifications",
    featureMedicineReminder3: "Pharmacy integration",
    featureEHR: "Electronic Health Records",
    featureEHRDesc: "Secure, comprehensive digital records accessible anytime, anywhere. Share with doctors instantly for better care.",
    featureEHR1: "Encrypted cloud storage",
    featureEHR2: "Smart organization & search",
    featureEHR3: "Instant doctor sharing",
    
    // SOS Section
    sosHeader: "Emergency SOS Service",
    sosDescription: "In case of medical emergency, our SOS feature instantly connects you to the nearest hospital and emergency services. Help is just one click away.",
    sosHowItWorks: "How Emergency SOS Works",
    sosStep1Title: "Press SOS Button",
    sosStep1Desc: "Tap the emergency SOS button to activate the emergency protocol instantly.",
    sosStep2Title: "Location Detection",
    sosStep2Desc: "We automatically detect your location and find the nearest hospital.",
    sosStep3Title: "Emergency Contact",
    sosStep3Desc: "We notify emergency services and the nearest hospital emergency department.",
    sosStep4Title: "Medical Assistance",
    sosStep4Desc: "Emergency medical teams receive your medical history and head to your location.",
    sosButtonText: "Emergency",
    sosButtonSOS: "SOS",
    sosActionDesc: "Press and hold the SOS button in case of medical emergency. This will immediately alert emergency services and the nearest hospital.",
    sosNoticeTitle: "⚠ Important Notice",
    sosNoticeText: "This is a demonstration feature. In a real emergency, please call your local emergency number (911, 112, etc.) immediately.",
    
    // Subscription
    subscriptionHeader: "Choose Your Health Plan",
    subscriptionDescription: "Select the perfect plan for your healthcare needs. All plans include our core features with varying levels of access and support.",
    planBasic: "Basic",
    planBasicDesc: "Essential healthcare features for everyone",
    planBasicPrice: "Free",
    planBasicFeature1: "Find and book appointments",
    planBasicFeature2: "Basic health tracking",
    planBasicFeature3: "Emergency SOS service",
    planBasicFeature4: "Access to general physicians",
    planBasicFeature5: "Basic health records",
    planBasicBtn: "Get Started",
    planPremium: "Premium",
    planPremiumTag: "Most Popular",
    planPremiumDesc: "Advanced features for comprehensive health management",
    planPremiumPrice: "/month",
    planPremiumFeature1: "Everything in Basic",
    planPremiumFeature2: "AI Health Tracker with insights",
    planPremiumFeature3: "Instant appointments (24/7)",
    planPremiumFeature4: "All specialist consultations",
    planPremiumFeature5: "Medicine reminder system",
    planPremiumFeature6: "Complete health analytics",
    planPremiumFeature7: "Priority emergency response",
    planPremiumFeature8: "Telemedicine consultations",
    planPremiumBtn: "Start Premium",
    planFamily: "Family",
    planFamilyDesc: "Complete healthcare solution for your entire family",
    planFamilyPrice: "/month",
    planFamilyFeature1: "Everything in Premium",
    planFamilyFeature2: "Up to 6 family members",
    planFamilyFeature3: "Family health dashboard",
    planFamilyFeature4: "Pediatric specialist access",
    planFamilyFeature5: "Family medicine reminders",
    planFamilyFeature6: "Shared health records",
    planFamilyFeature7: "Dedicated family health advisor",
    planFamilyFeature8: "Annual health checkup included",
    planFamilyBtn: "Choose Family",
    planBenefitsTitle: "Why Choose Health Sync Premium?",
    planBenefit1Title: "HIPAA Compliant",
    planBenefit1Desc: "Your health data is secure and protected with industry-standard encryption.",
    planBenefit2Title: "24/7 Support",
    planBenefit2Desc: "Round-the-clock medical support and emergency services available.",
    planBenefit3Title: "Top Doctors",
    planBenefit3Desc: "Access to board-certified specialists and top-rated healthcare providers.",
    
    // Footer
    footerDescription: "Your trusted healthcare companion providing smart medical support, online consultations, and emergency services for better health management.",
    footerQuickLinks: "Quick Links",
    footerContact: "Contact Info",
    footerCopyright: "All rights reserved.",
    
    // Modal
    modalHeader: "🚨 Emergency Alert",
    modalBody: "Contacting nearest hospital...",
    modalInfo: "Help is on the way! Please stay calm.",
    
    // Feedback Section
    feedbackHeader: "Patient Feedback",
    feedbackDescription: "Read what our patients say about their experience with Medinova.ai",
    feedback1: "Excellent service! The doctors are very professional and the platform is easy to use. Got my appointment quickly.",
    feedback2: "The AI health tracker helped me monitor my health better. Very satisfied with the emergency SOS feature.",
    feedback3: "Best healthcare platform! Medicine reminders are very helpful and the telemedicine consultations are convenient.",
    feedbackAuthor1: "Rajesh Kumar",
    feedbackAuthor2: "Priya Sharma",
    feedbackAuthor3: "Amit Singh",
    feedbackSince: "Patient since",
    
    // Footer Stats
    footerStatsTitle: "Hospital Statistics",
    footerTotalPatients: "Total Patients",
    footerAvailableBeds: "Available Beds",
    footerRecoveryRate: "Recovery Rate %",
    
    // Questions Page
    questionsHeroTitle: "Ask Your Health Questions",
    questionsHeroDesc: "Get answers from verified doctors. Ask questions, vote for important ones, and get expert medical advice.",
    askQuestionTitle: "Ask a Question",
    questionLabel: "Your Question",
    questionPlaceholder: "Type your health-related question here...",
    categoryLabel: "Category",
    selectCategory: "Select Category",
    categoryGeneral: "General Health",
    categoryCardiology: "Cardiology",
    categoryDermatology: "Dermatology",
    categoryNeurology: "Neurology",
    categoryPediatrics: "Pediatrics",
    categoryOrthopedics: "Orthopedics",
    categoryOther: "Other",
    submitQuestion: "Submit Question",
    topQuestionsTitle: "Top Questions",
    sortByVotes: "Most Voted",
    sortByRecent: "Most Recent",
    sortByAnswered: "Answered",
    answeredQuestionsTitle: "Answered by Verified Doctors",
    
    // Voice Input Page
    voiceHeroTitle: "Voice-Based Medical Input",
    voiceHeroDesc: "Speak in your regional language. Our AI will translate and convert your voice into medical records automatically.",
    voiceInputTitle: "Speak Your Medical Information",
    voiceInputDesc: "Select your language and start speaking. Your voice will be translated to English automatically.",
    selectInputLanguage: "Select Your Language:",
    langHindi: "Hindi (हिंदी)",
    langEnglish: "English",
    langBengali: "Bengali (বাংলা)",
    langTelugu: "Telugu (తెలుగు)",
    langTamil: "Tamil (தமிழ்)",
    langMarathi: "Marathi (मराठी)",
    langGujarati: "Gujarati (ગુજરાતી)",
    langKannada: "Kannada (ಕನ್ನಡ)",
    langPunjabi: "Punjabi (ਪੰਜਾਬੀ)",
    readyToRecord: "Ready to record",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    clearText: "Clear",
    recordingTime: "Recording: ",
    transcribedText: "Transcribed Text (Original Language):",
    transcriptionPlaceholder: "Your transcribed text will appear here...",
    translatedText: "Translated Text (English):",
    translationPlaceholder: "Translated text will appear here...",
    medicalFormTitle: "Medical Information Form",
    symptomsLabel: "Symptoms:",
    symptomsPlaceholder: "Describe your symptoms...",
    medicationsLabel: "Current Medications:",
    medicationsPlaceholder: "List your current medications...",
    allergiesLabel: "Allergies:",
    allergiesPlaceholder: "List any allergies...",
    medicalHistoryLabel: "Medical History:",
    medicalHistoryPlaceholder: "Describe your medical history...",
    fillFromVoice: "Fill from Voice Input",
    submitForm: "Submit Medical Information",
    instructionsTitle: "How to Use",
    instruction1: "Select your preferred regional language",
    instruction2: "Click 'Start Recording' and speak clearly",
    instruction3: "Your speech will be transcribed automatically",
    instruction4: "Text will be translated to English",
    instruction5: "Use 'Fill from Voice Input' to populate the form",
    instruction6: "Review and submit your medical information"
  },
  
  hi: {
    // Navigation
    navHome: "होम",
    navSpecialist: "विशेषज्ञ",
    navSubscription: "सदस्यता",
    navQuestions: "प्रश्न",
    navVoiceInput: "वॉइस इनपुट",
    navAbout: "के बारे में",
    navLogin: "लॉग इन",
    navSignup: "साइन अप",
    navBookAppointment: "अपॉइंटमेंट बुक करें",
    
    // Hero Section
    heroKicker: "विश्वसनीय डिजिटल देखभाल पारिस्थितिकी तंत्र",
    heroTitle: "आपकी सेहत, ",
    heroTitleSpan: "हमारी प्राथमिकता",
    heroSubtitle: "Health Sync के साथ स्वास्थ्य देखभाल के भविष्य का अनुभव करें। शीर्ष विशेषज्ञों के साथ अपॉइंटमेंट बुक करें, AI के साथ अपने स्वास्थ्य को ट्रैक करें, और जरूरत पड़ने पर आपातकालीन सहायता प्राप्त करें।",
    heroBookBtn: "अपॉइंटमेंट बुक करें",
    heroEmergencyBtn: "आपातकालीन SOS",
    heroStatsDoctors: "विशेषज्ञ डॉक्टर",
    heroStatsPatients: "खुश मरीज",
    heroStatsSupport: "आपातकालीन सहायता",
    heroHealthScore: "स्वास्थ्य स्कोर",
    heroHealthScoreValue: "98% स्थिर",
    
    // Specializations
    specHeader: "सही विशेषज्ञ खोजें",
    specDescription: "विभिन्न विशेषज्ञताओं में शीर्ष रेटेड डॉक्टरों से जुड़ें। हमारा प्लेटफॉर्म सुनिश्चित करता है कि आपको योग्य पेशेवरों से सर्वोत्तम देखभाल मिले।",
    specCardiology: "हृदय रोग विज्ञान",
    specCardiologyDesc: "हृदय और हृदय प्रणाली विशेषज्ञ",
    specDermatology: "त्वचा विज्ञान",
    specDermatologyDesc: "त्वचा, बाल और नाखून देखभाल विशेषज्ञ",
    specNeurology: "न्यूरोलॉजी",
    specNeurologyDesc: "मस्तिष्क और तंत्रिका तंत्र विशेषज्ञ",
    specGeneralPhysician: "सामान्य चिकित्सक",
    specGeneralPhysicianDesc: "प्राथमिक देखभाल और सामान्य स्वास्थ्य",
    specPediatrics: "बाल रोग",
    specPediatricsDesc: "बच्चों के लिए विशेष देखभाल",
    specOrthopedics: "आर्थोपेडिक्स",
    specOrthopedicsDesc: "हड्डी, जोड़ और मांसपेशी विशेषज्ञ",
    specDoctorsAvailable: "डॉक्टर उपलब्ध",
    specOnlineNow: "अभी ऑनलाइन",
    specBookConsultation: "सलाह बुक करें",
    specViewAll: "सभी विशेषज्ञता देखें",
    
    // Features
    featuresHeader: "स्मार्ट स्वास्थ्य देखभाल सुविधाएं",
    featuresDescription: "हमारी अभिनव सुविधाओं के साथ स्वास्थ्य देखभाल के भविष्य का अनुभव करें जो आपके स्वास्थ्य प्रबंधन को आसान, स्मार्ट और अधिक प्रभावी बनाने के लिए डिज़ाइन की गई हैं।",
    featureAITracker: "AI स्वास्थ्य ट्रैकर",
    featureAITrackerDesc: "उन्नत AI आपके महत्वपूर्ण संकेतों, लक्षणों और स्वास्थ्य पैटर्न की निगरानी करता है ताकि व्यक्तिगत अंतर्दृष्टि और प्रारंभिक चेतावनी अलर्ट प्रदान किए जा सकें।",
    featureAITracker1: "रीयल-टाइम निगरानी और अलर्ट",
    featureAITracker2: "सुरक्षित और HIPAA अनुपालन",
    featureAITracker3: "24/7 पहुंच",
    featureInstantAppointment: "तुरंत अपॉइंटमेंट",
    featureInstantAppointmentDesc: "तुरंत विशेषज्ञों के साथ अपॉइंटमेंट बुक करें। कोई प्रतीक्षा कक्ष नहीं, कोई परेशानी नहीं। मिनटों में सही डॉक्टर से जुड़ें।",
    featureInstantAppointment1: "स्मार्ट विशेषज्ञ मिलान",
    featureInstantAppointment2: "सुरक्षित वीडियो परामर्श",
    featureInstantAppointment3: "स्वचालित अनुसूची अनुस्मारक",
    featureMedicineReminder: "दवा अनुस्मारक",
    featureMedicineReminderDesc: "फिर कभी खुराक न चूकें। स्मार्ट अनुस्मारक सुनिश्चित करते हैं कि आप खुराक ट्रैकिंग के साथ सही समय पर सही दवा लें।",
    featureMedicineReminder1: "व्यक्तिगत अनुसूची",
    featureMedicineReminder2: "देखभाल करने वाले अधिसूचनाएं",
    featureMedicineReminder3: "फार्मेसी एकीकरण",
    featureEHR: "इलेक्ट्रॉनिक स्वास्थ्य रिकॉर्ड",
    featureEHRDesc: "सुरक्षित, व्यापक डिजिटल रिकॉर्ड कभी भी, कहीं भी पहुंच योग्य। बेहतर देखभाल के लिए तुरंत डॉक्टरों के साथ साझा करें।",
    featureEHR1: "एन्क्रिप्टेड क्लाउड स्टोरेज",
    featureEHR2: "स्मार्ट संगठन और खोज",
    featureEHR3: "तुरंत डॉक्टर साझाकरण",
    
    // SOS Section
    sosHeader: "आपातकालीन SOS सेवा",
    sosDescription: "चिकित्सा आपातकाल के मामले में, हमारी SOS सुविधा आपको तुरंत निकटतम अस्पताल और आपातकालीन सेवाओं से जोड़ती है। मदद सिर्फ एक क्लिक दूर है।",
    sosHowItWorks: "आपातकालीन SOS कैसे काम करता है",
    sosStep1Title: "SOS बटन दबाएं",
    sosStep1Desc: "आपातकालीन प्रोटोकॉल को तुरंत सक्रिय करने के लिए आपातकालीन SOS बटन दबाएं।",
    sosStep2Title: "स्थान का पता लगाना",
    sosStep2Desc: "हम स्वचालित रूप से आपके स्थान का पता लगाते हैं और निकटतम अस्पताल ढूंढते हैं।",
    sosStep3Title: "आपातकालीन संपर्क",
    sosStep3Desc: "हम आपातकालीन सेवाओं और निकटतम अस्पताल के आपातकालीन विभाग को सूचित करते हैं।",
    sosStep4Title: "चिकित्सा सहायता",
    sosStep4Desc: "आपातकालीन चिकित्सा टीमें आपके चिकित्सा इतिहास प्राप्त करती हैं और आपके स्थान पर जाती हैं।",
    sosButtonText: "आपातकाल",
    sosButtonSOS: "SOS",
    sosActionDesc: "चिकित्सा आपातकाल के मामले में SOS बटन को दबाकर रखें। यह तुरंत आपातकालीन सेवाओं और निकटतम अस्पताल को सचेत करेगा।",
    sosNoticeTitle: "⚠ महत्वपूर्ण सूचना",
    sosNoticeText: "यह एक प्रदर्शन सुविधा है। वास्तविक आपातकाल में, कृपया तुरंत अपने स्थानीय आपातकालीन नंबर (911, 112, आदि) पर कॉल करें।",
    
    // Subscription
    subscriptionHeader: "अपना स्वास्थ्य योजना चुनें",
    subscriptionDescription: "अपनी स्वास्थ्य देखभाल आवश्यकताओं के लिए सही योजना चुनें। सभी योजनाओं में पहुंच और सहायता के विभिन्न स्तरों के साथ हमारी मुख्य सुविधाएं शामिल हैं।",
    planBasic: "बेसिक",
    planBasicDesc: "सभी के लिए आवश्यक स्वास्थ्य देखभाल सुविधाएं",
    planBasicPrice: "मुफ्त",
    planBasicFeature1: "अपॉइंटमेंट खोजें और बुक करें",
    planBasicFeature2: "बुनियादी स्वास्थ्य ट्रैकिंग",
    planBasicFeature3: "आपातकालीन SOS सेवा",
    planBasicFeature4: "सामान्य चिकित्सकों तक पहुंच",
    planBasicFeature5: "बुनियादी स्वास्थ्य रिकॉर्ड",
    planBasicBtn: "शुरू करें",
    planPremium: "प्रीमियम",
    planPremiumTag: "सबसे लोकप्रिय",
    planPremiumDesc: "व्यापक स्वास्थ्य प्रबंधन के लिए उन्नत सुविधाएं",
    planPremiumPrice: "/महीना",
    planPremiumFeature1: "बेसिक में सब कुछ",
    planPremiumFeature2: "अंतर्दृष्टि के साथ AI स्वास्थ्य ट्रैकर",
    planPremiumFeature3: "तुरंत अपॉइंटमेंट (24/7)",
    planPremiumFeature4: "सभी विशेषज्ञ परामर्श",
    planPremiumFeature5: "दवा अनुस्मारक प्रणाली",
    planPremiumFeature6: "पूर्ण स्वास्थ्य विश्लेषण",
    planPremiumFeature7: "प्राथमिकता आपातकालीन प्रतिक्रिया",
    planPremiumFeature8: "टेलीमेडिसिन परामर्श",
    planPremiumBtn: "प्रीमियम शुरू करें",
    planFamily: "परिवार",
    planFamilyDesc: "आपके पूरे परिवार के लिए पूर्ण स्वास्थ्य देखभाल समाधान",
    planFamilyPrice: "/महीना",
    planFamilyFeature1: "प्रीमियम में सब कुछ",
    planFamilyFeature2: "6 परिवार के सदस्यों तक",
    planFamilyFeature3: "परिवार स्वास्थ्य डैशबोर्ड",
    planFamilyFeature4: "बाल रोग विशेषज्ञ पहुंच",
    planFamilyFeature5: "परिवार दवा अनुस्मारक",
    planFamilyFeature6: "साझा स्वास्थ्य रिकॉर्ड",
    planFamilyFeature7: "समर्पित परिवार स्वास्थ्य सलाहकार",
    planFamilyFeature8: "वार्षिक स्वास्थ्य जांच शामिल",
    planFamilyBtn: "परिवार चुनें",
    planBenefitsTitle: "Health Sync Premium क्यों चुनें?",
    planBenefit1Title: "HIPAA अनुपालन",
    planBenefit1Desc: "आपका स्वास्थ्य डेटा उद्योग-मानक एन्क्रिप्शन के साथ सुरक्षित और संरक्षित है।",
    planBenefit2Title: "24/7 सहायता",
    planBenefit2Desc: "चौबीसों घंटे चिकित्सा सहायता और आपातकालीन सेवाएं उपलब्ध।",
    planBenefit3Title: "शीर्ष डॉक्टर",
    planBenefit3Desc: "बोर्ड-प्रमाणित विशेषज्ञों और शीर्ष रेटेड स्वास्थ्य देखभाल प्रदाताओं तक पहुंच।",
    
    // Footer
    footerDescription: "आपका विश्वसनीय स्वास्थ्य देखभाल साथी जो बेहतर स्वास्थ्य प्रबंधन के लिए स्मार्ट चिकित्सा सहायता, ऑनलाइन परामर्श और आपातकालीन सेवाएं प्रदान करता है।",
    footerQuickLinks: "त्वरित लिंक",
    footerContact: "संपर्क जानकारी",
    footerCopyright: "सभी अधिकार सुरक्षित।",
    
    // Modal
    modalHeader: "🚨 आपातकालीन अलर्ट",
    modalBody: "निकटतम अस्पताल से संपर्क कर रहे हैं...",
    modalInfo: "मदद रास्ते में है! कृपया शांत रहें।",
    
    // Feedback Section
    feedbackHeader: "रोगी प्रतिक्रिया",
    feedbackDescription: "Medinova.ai के साथ अपने अनुभव के बारे में हमारे रोगी क्या कहते हैं, पढ़ें",
    feedback1: "उत्कृष्ट सेवा! डॉक्टर बहुत पेशेवर हैं और प्लेटफॉर्म उपयोग में आसान है। मुझे जल्दी अपॉइंटमेंट मिल गया।",
    feedback2: "AI स्वास्थ्य ट्रैकर ने मुझे अपने स्वास्थ्य की बेहतर निगरानी करने में मदद की। आपातकालीन SOS सुविधा से बहुत संतुष्ट हूं।",
    feedback3: "सर्वश्रेष्ठ स्वास्थ्य देखभाल प्लेटफॉर्म! दवा अनुस्मारक बहुत उपयोगी हैं और टेलीमेडिसिन परामर्श सुविधाजनक हैं।",
    feedbackAuthor1: "राजेश कुमार",
    feedbackAuthor2: "प्रिया शर्मा",
    feedbackAuthor3: "अमित सिंह",
    feedbackSince: "रोगी",
    
    // Footer Stats
    footerStatsTitle: "अस्पताल आंकड़े",
    footerTotalPatients: "कुल रोगी",
    footerAvailableBeds: "उपलब्ध बिस्तर",
    footerRecoveryRate: "रिकवरी दर %",
    
    // Questions Page
    questionsHeroTitle: "अपने स्वास्थ्य प्रश्न पूछें",
    questionsHeroDesc: "सत्यापित डॉक्टरों से उत्तर प्राप्त करें। प्रश्न पूछें, महत्वपूर्ण लोगों के लिए वोट करें, और विशेषज्ञ चिकित्सा सलाह प्राप्त करें।",
    askQuestionTitle: "एक प्रश्न पूछें",
    questionLabel: "आपका प्रश्न",
    questionPlaceholder: "अपना स्वास्थ्य संबंधी प्रश्न यहाँ टाइप करें...",
    categoryLabel: "श्रेणी",
    selectCategory: "श्रेणी चुनें",
    categoryGeneral: "सामान्य स्वास्थ्य",
    categoryCardiology: "हृदय रोग विज्ञान",
    categoryDermatology: "त्वचा विज्ञान",
    categoryNeurology: "न्यूरोलॉजी",
    categoryPediatrics: "बाल रोग",
    categoryOrthopedics: "आर्थोपेडिक्स",
    categoryOther: "अन्य",
    submitQuestion: "प्रश्न सबमिट करें",
    topQuestionsTitle: "शीर्ष प्रश्न",
    sortByVotes: "सबसे अधिक वोट",
    sortByRecent: "सबसे हाल का",
    sortByAnswered: "उत्तर दिया गया",
    answeredQuestionsTitle: "सत्यापित डॉक्टरों द्वारा उत्तर दिया गया",
    
    // Voice Input Page
    voiceHeroTitle: "वॉइस-आधारित चिकित्सा इनपुट",
    voiceHeroDesc: "अपनी क्षेत्रीय भाषा में बोलें। हमारी AI आपकी आवाज़ को स्वचालित रूप से अनुवाद करेगी और चिकित्सा रिकॉर्ड में बदल देगी।",
    voiceInputTitle: "अपनी चिकित्सा जानकारी बोलें",
    voiceInputDesc: "अपनी भाषा चुनें और बोलना शुरू करें। आपकी आवाज़ स्वचालित रूप से अंग्रेजी में अनुवादित हो जाएगी।",
    selectInputLanguage: "अपनी भाषा चुनें:",
    langHindi: "हिंदी (हिंदी)",
    langEnglish: "अंग्रेजी",
    langBengali: "बंगाली (বাংলা)",
    langTelugu: "तेलुगु (తెలుగు)",
    langTamil: "तमिल (தமிழ்)",
    langMarathi: "मराठी (मराठी)",
    langGujarati: "गुजराती (ગુજરાતી)",
    langKannada: "कन्नड़ (ಕನ್ನಡ)",
    langPunjabi: "पंजाबी (ਪੰਜਾਬੀ)",
    readyToRecord: "रिकॉर्ड करने के लिए तैयार",
    startRecording: "रिकॉर्डिंग शुरू करें",
    stopRecording: "रिकॉर्डिंग रोकें",
    clearText: "साफ करें",
    recordingTime: "रिकॉर्डिंग: ",
    transcribedText: "ट्रांसक्राइब किया गया टेक्स्ट (मूल भाषा):",
    transcriptionPlaceholder: "आपका ट्रांसक्राइब किया गया टेक्स्ट यहाँ दिखाई देगा...",
    translatedText: "अनुवादित टेक्स्ट (अंग्रेजी):",
    translationPlaceholder: "अनुवादित टेक्स्ट यहाँ दिखाई देगा...",
    medicalFormTitle: "चिकित्सा जानकारी फॉर्म",
    symptomsLabel: "लक्षण:",
    symptomsPlaceholder: "अपने लक्षणों का वर्णन करें...",
    medicationsLabel: "वर्तमान दवाएं:",
    medicationsPlaceholder: "अपनी वर्तमान दवाओं की सूची बनाएं...",
    allergiesLabel: "एलर्जी:",
    allergiesPlaceholder: "कोई एलर्जी सूचीबद्ध करें...",
    medicalHistoryLabel: "चिकित्सा इतिहास:",
    medicalHistoryPlaceholder: "अपने चिकित्सा इतिहास का वर्णन करें...",
    fillFromVoice: "वॉइस इनपुट से भरें",
    submitForm: "चिकित्सा जानकारी सबमिट करें",
    instructionsTitle: "कैसे उपयोग करें",
    instruction1: "अपनी पसंदीदा क्षेत्रीय भाषा चुनें",
    instruction2: "'रिकॉर्डिंग शुरू करें' पर क्लिक करें और स्पष्ट रूप से बोलें",
    instruction3: "आपका भाषण स्वचालित रूप से ट्रांसक्राइब हो जाएगा",
    instruction4: "टेक्स्ट अंग्रेजी में अनुवादित हो जाएगा",
    instruction5: "फॉर्म भरने के लिए 'वॉइस इनपुट से भरें' का उपयोग करें",
    instruction6: "अपनी चिकित्सा जानकारी की समीक्षा करें और सबमिट करें"
  }
};

// Function to get translation
function getTranslation(key, lang = 'en') {
  return translations[lang] && translations[lang][key] ? translations[lang][key] : translations['en'][key];
}

// Function to set language
function setLanguage(lang) {
  localStorage.setItem('selectedLanguage', lang);
}

// Function to get current language
function getCurrentLanguage() {
  return localStorage.getItem('selectedLanguage') || 'en';
}
